kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${APPLICATION_NAME}
objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      annotations:
        description: Stream of application images
      name: ${APPLICATION_NAME}
      labels:
        template: ${APPLICATION_NAME}
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${APPLICATION_NAME}
      annotations:
        description: Defines how to build the application from git
        template.alpha.openshift.io/wait-for-ready: "true"
      labels:
        template: ${APPLICATION_NAME}
    spec:
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
        contextDir: "${CONTEXT_DIRECTORY}"
      output:
        to:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python:${PYTHON_VERSION}
            namespace: openshift
        type: Source
      triggers:
      - type: Generic
        generic:
          secret: ${GITHUB_WEBHOOK_SECRET}
      - type: GitHub
        github:
          secret: ${GITHUB_WEBHOOK_SECRET}
      - type: ImageChange
      - type: ConfigChange
 
parameters:
  - name: APPLICATION_NAME
    displayName: Application Name
    description: The name of the application - used for resource names and labels
    value: vote-app
    required: true
  - name: SOURCE_REPOSITORY_URL
    displayName: Source Repository URL
    description: The URL for the application git repository
    value: https://github.com/kringen/openshift-jenkins-ci-cd
    required: true
  - name: CONTEXT_DIRECTORY
    displayName: Context Directory
    description: Directory containing application in source repository.
    value: /applications/vote
    required: false
  - name: PYTHON_VERSION
    displayName: Python Version
    description: Python builder image version
    value: 3.8-ubi8
  - name: GITHUB_WEBHOOK_SECRET
    description: A secret string used to configure the GitHub webhook
    generate: expression 
    from: "[a-zA-Z0-9]{40}" 
  - name: REPLICA_COUNT
    description: Number of replicas to run
    value: "1"
    required: true
  - name: PORT
    description: Port on which the application listens.
    value: "8080"
    required: false
  - name: RESOURCE_LIMIT_MEMORY
    description: "Limit the memory consumed by a pod before it is destroyed and re-created."
    value: 512Mi